export const shippingRates = [
  { province: "Aceh", destinationCity: "Banda Aceh", cost: 85000 },
  { province: "Sumatera Utara", destinationCity: "Medan", cost: 60000 },
  { province: "Sumatera Barat", destinationCity: "Padang", cost: 55000 },
  { province: "Riau", destinationCity: "Pekanbaru", cost: 48000 },
  { province: "Kepulauan Riau", destinationCity: "Batam", cost: 50000 },
  { province: "Jambi", destinationCity: "Jambi", cost: 45000 },
  { province: "Sumatera Selatan", destinationCity: "Palembang", cost: 40000 },
  { province: "Bengkulu", destinationCity: "Bengkulu", cost: 55000 },
  { province: "Lampung", destinationCity: "Bandar Lampung", cost: 28000 },
  { province: "Bangka Belitung", destinationCity: "Pangkal Pinang", cost: 50000 },
  { province: "DKI Jakarta", destinationCity: "Jakarta", cost: 15000 },
  { province: "Banten", destinationCity: "Tangerang / Serang", cost: 16000 },
  { province: "Jawa Barat", destinationCity: "Bandung / Bekasi", cost: 14000 },
  { province: "Jawa Tengah", destinationCity: "Semarang", cost: 25000 },
  { province: "DI Yogyakarta", destinationCity: "Yogyakarta", cost: 25000 },
  { province: "Jawa Timur", destinationCity: "Surabaya", cost: 30000 },
  { province: "Bali", destinationCity: "Denpasar", cost: 40000 },
  { province: "Nusa Tenggara Barat", destinationCity: "Mataram", cost: 50000 },
  { province: "Nusa Tenggara Timur", destinationCity: "Kupang", cost: 80000 },
  { province: "Kalimantan Barat", destinationCity: "Pontianak", cost: 50000 },
  { province: "Kalimantan Tengah", destinationCity: "Palangkaraya", cost: 60000 },
  { province: "Kalimantan Selatan", destinationCity: "Banjarmasin", cost: 60000 },
  { province: "Kalimantan Timur", destinationCity: "Balikpapan", cost: 65000 },
  { province: "Kalimantan Utara", destinationCity: "Tarakan", cost: 80000 },
  { province: "Sulawesi Utara", destinationCity: "Manado", cost: 90000 },
  { province: "Gorontalo", destinationCity: "Gorontalo", cost: 80000 },
  { province: "Sulawesi Tengah", destinationCity: "Palu", cost: 75000 },
  { province: "Sulawesi Barat", destinationCity: "Mamuju", cost: 75000 },
  { province: "Sulawesi Selatan", destinationCity: "Makassar", cost: 70000 },
  { province: "Sulawesi Tenggara", destinationCity: "Kendari", cost: 80000 },
  { province: "Maluku", destinationCity: "Ambon", cost: 110000 },
  { province: "Maluku Utara", destinationCity: "Ternate", cost: 120000 },
  { province: "Papua Barat", destinationCity: "Manokwari", cost: 140000 },
  { province: "Papua Barat Daya", destinationCity: "Sorong", cost: 130000 },
  { province: "Papua", destinationCity: "Jayapura", cost: 150000 },
  { province: "Papua Tengah", destinationCity: "Nabire", cost: 150000 },
  { province: "Papua Pegunungan", destinationCity: "Wamena", cost: 220000 },
  { province: "Papua Selatan", destinationCity: "Merauke", cost: 160000 },
];

export function getShippingRateByProvince(province) {
  return shippingRates.find((rate) => rate.province === province) || null;
}
